### ISSUE TITLE
clicking user link in upper right logs out

### ISSUE THREAD

**Issue by natgaertner** [hipinion/conductor#3]
After I log in, if I click my username in the titlebar, it logs me out and takes me to the login page.
I imagine because the html for the link is
`<a href="/logout">pantsoclock</a>`
Is this intended? I expected it to take me to my user profile but I am not the best web designer.

**Comment by nkozyra** [comment]
it's temporary

there's no real front-end framework so no reason to worry about it

**Comment by natgaertner** [comment]
Is there a profile page (look I just want to set my avatar)?

**Comment by nkozyra** [comment]
/profile

seems persnickety to update but fine to set so make a good choice

**Comment by natgaertner** [comment]
I have the greatest avatar now and conductor is good
