### ISSUE TITLE
Posts not appearing

### ISSUE THREAD

**Issue by natgaertner** [hipinion/conductor#4]
I can make a thread, like:
https://hipin.io/forums/shit-postin/xuoqhpyv-whats-for-lunch-today-everyone
And it renders the title and subtitle, but the text seems to be missing

Similarly, when I respond to a thread, the post does not seem to get added (but I notice the threads get re-ordered, possibly indicating that their last updated time is getting set?)
I experimented with  posting in a few threads.
I definitely posted in this one but can only see Gloom's posts: https://hipin.io/forums/better-boarding/rdmdvahd--conductor-the-state

This is the same behavior in chrome and firefox.
I'm not seeing any failed requests or js errors in the console. Lemme know if you need any other debugging info

**Comment by nkozyra** [comment]
Working as intended.

**Comment by natgaertner** [comment]
is good joke.

**Comment by nkozyra** [comment]
works fine

**Comment by nkozyra** [comment]
(post again)
